id: P006640
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG14647
  title: གསུང་འབུམ། སྐྱོབ་པ་འཇིག་རྟེན་མགོན་པོ།
  author: ''
  volumes:
    14bce5faafc94bbbbe1c93b6944a1b4c:
      image_group_id: I1KG15708
      title: ''
      volume_number: 1
      total_pages: 748
    2ba10b8d8bab4a1fa3db0468cc03399f:
      image_group_id: I1KG15709
      title: ''
      volume_number: 2
      total_pages: 768
    3aa94130d3c34ed082a420756b28f1b6:
      image_group_id: I1KG15710
      title: ''
      volume_number: 3
      total_pages: 814
    458f9a6ed367410bb059afaab2a08d8e:
      image_group_id: I1KG15711
      title: ''
      volume_number: 4
      total_pages: 778
