id: I488A2222
legacy_id: P006640
ocr_import_info:
  bdrc_scan_id: W1KG14647
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T15:56:14'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T07:05:04.906197+00:00'
last_modified: 2022-08-31 15:07:37.850474
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG14647
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG14647
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། སྐྱོབ་པ་འཇིག་རྟེན་མགོན་པོ།
  author: སྐྱོབ་པ་འཇིག་རྟེན་གསུམ་མགོན།
statistics:
  ocr_word_mean_confidence_index: 0.9160668887787248
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG15709:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15709
      total_pages: 768
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG15709.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9003919339913191
    legacy_id: v002
  I1KG15710:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15710
      total_pages: 814
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG15710.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9202600582876866
    legacy_id: v003
  I1KG15708:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15708
      total_pages: 748
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG15708.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.92287042461885
    legacy_id: v001
  I1KG15711:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15711
      total_pages: 778
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1KG15711.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9211156063479831
    legacy_id: v004
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
